In [10]:
import pandas as pd
df = pd.read_excel("cereal_data.xls", "cereal")
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,Corn Chex,R,C,110.0,2.0,0.0,280.0,0.0,22.0,3.0,25.0,25.0,1.0,1.0,1.00,41.445019
1,Corn Flakes,K,C,100.0,2.0,0.0,290.0,1.0,21.0,2.0,35.0,25.0,1.0,1.0,1.00,45.863324
2,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.0,1.00,40.560159
3,Special K,K,NaN,110.0,6.0,0.0,230.0,1.0,16.0,3.0,55.0,25.0,1.0,1.0,1.00,53.131324
4,Multi-Grain Cheerios,G,C,100.0,2.0,1.0,220.0,2.0,15.0,6.0,90.0,25.0,1.0,1.0,1.00,40.105965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Grape Nuts Flakes,P,C,100.0,3.0,1.0,140.0,3.0,15.0,5.0,85.0,25.0,3.0,1.0,0.88,52.076897
73,Rice Chex,R,C,NaN,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.0,1.13,41.998933
74,Cheerios,G,C,110.0,6.0,2.0,290.0,2.0,17.0,1.0,105.0,25.0,1.0,1.0,1.25,50.764999
75,Honey-comb,P,C,110.0,1.0,0.0,180.0,0.0,14.0,11.0,35.0,25.0,1.0,1.0,1.33,28.742414
76,Kix,G,C,110.0,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.0,1.50,39.241114

In [11]:
df.shape

(77, 16)

In [12]:
df.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,75.000000,76.000000,75.000000,75.000000,75.000000,76.000000,76.000000,76.000000,74.000000,76.000000,77.000000
mean,106.842105,2.539474,1.013333,159.671053,2.156000,14.600000,6.933333,96.092105,28.289474,2.210526,1.030811,0.821316,42.665705
std,19.610237,1.100797,1.019981,84.389318,2.415224,4.335585,4.503252,71.760375,22.487813,0.837708,0.153416,0.234250,14.047289
min,50.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,128.750000,0.500000,12.000000,3.000000,40.000000,25.000000,1.000000,1.000000,0.670000,33.174094
50%,110.000000,2.500000,1.000000,180.000000,1.500000,14.000000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.400208
75%,110.000000,3.000000,2.000000,212.500000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.828392
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [14]:
df.isnull().sum()

name        0
mfr         4
type        6
calories    1
protein     1
fat         2
sodium      1
fiber       2
carbo       2
sugars      2
potass      1
vitamins    1
shelf       1
weight      3
cups        1
rating      0
dtype: int64

In [15]:
dropped_table = df.fillna(0)
dropped_table

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,Corn Chex,R,C,110.0,2.0,0.0,280.0,0.0,22.0,3.0,25.0,25.0,1.0,1.0,1.00,41.445019
1,Corn Flakes,K,C,100.0,2.0,0.0,290.0,1.0,21.0,2.0,35.0,25.0,1.0,1.0,1.00,45.863324
2,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.0,1.00,40.560159
3,Special K,K,0,110.0,6.0,0.0,230.0,1.0,16.0,3.0,55.0,25.0,1.0,1.0,1.00,53.131324
4,Multi-Grain Cheerios,G,C,100.0,2.0,1.0,220.0,2.0,15.0,6.0,90.0,25.0,1.0,1.0,1.00,40.105965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Grape Nuts Flakes,P,C,100.0,3.0,1.0,140.0,3.0,15.0,5.0,85.0,25.0,3.0,1.0,0.88,52.076897
73,Rice Chex,R,C,0.0,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.0,1.13,41.998933
74,Cheerios,G,C,110.0,6.0,2.0,290.0,2.0,17.0,1.0,105.0,25.0,1.0,1.0,1.25,50.764999
75,Honey-comb,P,C,110.0,1.0,0.0,180.0,0.0,14.0,11.0,35.0,25.0,1.0,1.0,1.33,28.742414
76,Kix,G,C,110.0,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.0,1.50,39.241114

In [16]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,Corn Chex,R,C,110.0,2.0,0.0,280.0,0.0,22.0,3.0,25.0,25.0,1.0,1.0,1.00,41.445019
1,Corn Flakes,K,C,100.0,2.0,0.0,290.0,1.0,21.0,2.0,35.0,25.0,1.0,1.0,1.00,45.863324
2,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.0,1.00,40.560159
3,Special K,K,NaN,110.0,6.0,0.0,230.0,1.0,16.0,3.0,55.0,25.0,1.0,1.0,1.00,53.131324
4,Multi-Grain Cheerios,G,C,100.0,2.0,1.0,220.0,2.0,15.0,6.0,90.0,25.0,1.0,1.0,1.00,40.105965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Grape Nuts Flakes,P,C,100.0,3.0,1.0,140.0,3.0,15.0,5.0,85.0,25.0,3.0,1.0,0.88,52.076897
73,Rice Chex,R,C,NaN,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.0,1.13,41.998933
74,Cheerios,G,C,110.0,6.0,2.0,290.0,2.0,17.0,1.0,105.0,25.0,1.0,1.0,1.25,50.764999
75,Honey-comb,P,C,110.0,1.0,0.0,180.0,0.0,14.0,11.0,35.0,25.0,1.0,1.0,1.33,28.742414
76,Kix,G,C,110.0,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.0,1.50,39.241114

In [17]:
df.isnull().sum()

name        0
mfr         4
type        6
calories    1
protein     1
fat         2
sodium      1
fiber       2
carbo       2
sugars      2
potass      1
vitamins    1
shelf       1
weight      3
cups        1
rating      0
dtype: int64

In [18]:
dropped_table.isnull().sum()

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [28]:
df["weight"].mean()

1.0308108108108107

In [30]:
copied_df = df

In [31]:
copied_df.fillna({
    "weight": copied_df["weight"].mean()
})

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,Corn Chex,R,C,110.0,2.0,0.0,280.0,0.0,22.0,3.0,25.0,25.0,1.0,1.0,1.00,41.445019
1,Corn Flakes,K,C,100.0,2.0,0.0,290.0,1.0,21.0,2.0,35.0,25.0,1.0,1.0,1.00,45.863324
2,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.0,1.00,40.560159
3,Special K,K,NaN,110.0,6.0,0.0,230.0,1.0,16.0,3.0,55.0,25.0,1.0,1.0,1.00,53.131324
4,Multi-Grain Cheerios,G,C,100.0,2.0,1.0,220.0,2.0,15.0,6.0,90.0,25.0,1.0,1.0,1.00,40.105965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Grape Nuts Flakes,P,C,100.0,3.0,1.0,140.0,3.0,15.0,5.0,85.0,25.0,3.0,1.0,0.88,52.076897
73,Rice Chex,R,C,NaN,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.0,1.13,41.998933
74,Cheerios,G,C,110.0,6.0,2.0,290.0,2.0,17.0,1.0,105.0,25.0,1.0,1.0,1.25,50.764999
75,Honey-comb,P,C,110.0,1.0,0.0,180.0,0.0,14.0,11.0,35.0,25.0,1.0,1.0,1.33,28.742414
76,Kix,G,C,110.0,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.0,1.50,39.241114

In [32]:
copied_df.isnull().sum()

name        0
mfr         4
type        6
calories    1
protein     1
fat         2
sodium      1
fiber       2
carbo       2
sugars      2
potass      1
vitamins    1
shelf       1
weight      3
cups        1
rating      0
dtype: int64

In [48]:
newOne = df.fillna({
    "weight": df["weight"].mean()
})

In [49]:
df.isnull().sum()

name        0
mfr         4
type        6
calories    1
protein     1
fat         2
sodium      1
fiber       2
carbo       2
sugars      2
potass      1
vitamins    1
shelf       1
weight      3
cups        1
rating      0
dtype: int64

In [50]:
newOne.isnull().sum()

name        0
mfr         4
type        6
calories    1
protein     1
fat         2
sodium      1
fiber       2
carbo       2
sugars      2
potass      1
vitamins    1
shelf       1
weight      0
cups        1
rating      0
dtype: int64

In [51]:
result = df.head(10)
result

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,Corn Chex,R,C,110.0,2.0,0.0,280.0,0.0,22.0,3.0,25.0,25.0,1.0,1.0,1.0,41.445019
1,Corn Flakes,K,C,100.0,2.0,0.0,290.0,1.0,21.0,2.0,35.0,25.0,1.0,1.0,1.0,45.863324
2,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.0,1.0,40.560159
3,Special K,K,NaN,110.0,6.0,0.0,230.0,1.0,16.0,3.0,55.0,25.0,1.0,1.0,1.0,53.131324
4,Multi-Grain Cheerios,G,C,100.0,2.0,1.0,220.0,2.0,15.0,6.0,90.0,25.0,1.0,1.0,1.0,40.105965
5,Wheaties,G,C,100.0,3.0,1.0,200.0,3.0,17.0,3.0,110.0,25.0,1.0,NaN,1.0,51.592193
6,Cream of Wheat (Quick),N,H,100.0,3.0,0.0,80.0,1.0,21.0,0.0,-1.0,0.0,2.0,1.0,1.0,64.533816
7,Corn Pops,K,C,110.0,1.0,0.0,90.0,1.0,13.0,12.0,20.0,25.0,2.0,1.0,1.0,35.782791
8,Trix,G,C,110.0,1.0,1.0,140.0,0.0,13.0,12.0,25.0,25.0,2.0,1.0,1.0,27.753301
9,Froot Loops,K,C,110.0,2.0,1.0,125.0,1.0,11.0,13.0,30.0,25.0,2.0,1.0,1.0,32.207582

In [53]:
result = df.tail(10)
result

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
67,Just Right Fruit & Nut,NaN,C,140.0,3.0,1.0,170.0,2.0,20.0,9.0,95.0,100.0,3.0,1.30,0.75,36.471512
68,Raisin Bran,NaN,C,120.0,3.0,1.0,210.0,5.0,14.0,12.0,240.0,25.0,2.0,1.33,0.75,39.259197
69,Basic 4,G,C,130.0,3.0,2.0,210.0,2.0,18.0,8.0,100.0,25.0,3.0,1.33,0.75,37.038562
70,Frosted Mini-Wheats,NaN,C,100.0,NaN,0.0,0.0,3.0,14.0,7.0,100.0,25.0,2.0,1.00,NaN,58.345141
71,Golden Crisp,P,C,100.0,2.0,0.0,45.0,0.0,11.0,15.0,40.0,25.0,1.0,1.00,0.88,35.252444
72,Grape Nuts Flakes,P,C,100.0,3.0,1.0,140.0,3.0,15.0,5.0,85.0,25.0,3.0,1.00,0.88,52.076897
73,Rice Chex,R,C,NaN,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.00,1.13,41.998933
74,Cheerios,G,C,110.0,6.0,2.0,290.0,2.0,17.0,1.0,105.0,25.0,1.0,1.00,1.25,50.764999
75,Honey-comb,P,C,110.0,1.0,0.0,180.0,0.0,14.0,11.0,35.0,25.0,1.0,1.00,1.33,28.742414
76,Kix,G,C,110.0,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.00,1.50,39.241114